version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: db
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: queue
    restart: on-failure
    ports:
      - "6379:6379"

  bonus:
    container_name: bonus
    build:
      context: src/bonus
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8050:8050"

  flight:
    container_name: flight
    build:
      context: src/flight
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8060:8060"

  ticket:
    container_name: ticket
    build:
      context: src/ticket
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8070:8070"

  gateway:
    container_name: gateway
    build:
      context: src/gateway
      dockerfile: Dockerfile
    depends_on:
      - bonus
      - flight
      - ticket
      - redis
    ports:
      - "8080:8080"

volumes:
  db-data: